In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('all_props.csv')

In [3]:
df

,Symbol,AtomicMass,AtomicRadius,Electronegativity,IonizationEnergy,ElectronAffinity,Polarizability,results_per_total,results_per_li,LiSites,CounterIonSites,results_per_counter_ion,Result
0,Ga,69.72300,187,1.81,5.999,0.300,50.00,0.011710,0.011710,1,3,0.011710,11.709881
1,Cu,63.55000,140,1.90,7.726,1.228,46.50,0.014244,0.014244,2,6,0.014244,14.243751
2,Ag,107.86800,172,1.93,7.576,1.302,55.00,0.011542,0.011542,1,1,0.011542,11.542257
3,Pd,106.42000,202,2.20,8.337,0.557,26.14,0.015710,0.015710,3,1,0.015710,15.709607
4,In,114.81800,193,1.78,5.786,0.300,65.00,0.017291,0.017291,3,1,0.017291,17.290921
...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Tl,204.38300,196,1.62,6.108,0.200,66.00,0.010646,0.010646,1,3,0.010646,10.645902
448,Pm,144.91276,236,0.00,5.550,0.000,200.00,0.031452,0.031452,1,3,0.031452,31.451888
449,Mg,24.30500,173,1.31,7.646,0.000,71.20,0.010113,0.010113,1,149,0.010113,10.112955
450,Pt,195.08000,209,2.28,9.000,2.128,48.00,0.014012,0.014012,3,1,0.014012,14.011933
451,O,15.99900,152,3.44,13.618,1.461,5.30,0.000753,0.000753,1,8,0.000753,0.753340

In [ ]:
grouped_df = df.groupby('Symbol')
for symbol, group in grouped_df:
    print(f"Category: {symbol}")
    # print(group['Result'].max())
    # print(group['Result'].min())
    print(group['Result'])
    print('---------------------')
    print(group['Result'].max() - group['Result'].min())
    print("\n")

Category: Ac
1.8325049999999994


Category: Ag
4.7035862139999995


Category: Al
15.515299697


Category: As
9.151251233


Category: Au
8.041501978


Category: B
9.878161117


Category: Be
12.826753691


Category: Bi
5.343349936


Category: Br
2.242657846


Category: C
10.531022351


Category: Ca
13.830093017


Category: Cd
7.010016601


Category: Ce
7.425261416


Category: Cl
2.2630572530000004


Category: Co
0.37414422599999986


Category: Cr
0.19359845799999986


Category: Cu
3.4669436000000022


Category: Dy
8.786012410000001


Category: Er
1.2963415900000008


Category: Eu
12.605864310000001


Category: F
6.08645224


Category: Fe
0.6449081959999998


Category: Ga
14.247017939000001


Category: Gd
3.5765564199999993


Category: Ge
12.982911522


Category: H
0.0


Category: Hf
13.322236665


Category: Hg
8.69540947


Category: Ho
1.6748925700000008


Category: I
1.437211515


Category: In
9.112348698000002


Category: Ir
8.283748059


Category: La
0.468855480000002


Category: Li
17.537799448


Category: Lu
4.1422728499999995


Category: Mg
14.942224516000001


Category: Mn
0.0


Category: Mo
0.0


Category: N
9.173343349


Category: Nb
1.9644471500000016


Category: Nd
0.0


Category: Ni
0.994653338


Category: Np
3.6947259799999994


Category: O
10.649549327


Category: P
10.487096514000001


Category: Pa
0.0


Category: Pb
12.461351927


Category: Pd
13.934818067999998


Category: Pm
14.259234810000002


Category: Pr
7.762740109999999


Category: Pt
6.6682526950000005


Category: Pu
2.7026422599999993


Category: Re
3.0215631189999996


Category: Rh
17.151025061


Category: S
11.064367731


Category: Sb
7.157623138999999


Category: Sc
0.0


Category: Se
0.0


Category: Si
13.27759119


Category: Sm
14.414318680000001


Category: Sn
11.891021475999999


Category: Tb
28.788638671


Category: Tc
0.30155551700000016


Category: Te
10.553770190000002


Category: Th
0.0


Category: Tl
7.236620949999999


Category: Tm
0.123825140000001


Category: U
0.0


Category: W
2.446759525


Category: Y
4.360208100000001


Category: Yb
4.13237882


Category: Zn
12.996936455


Category: Zr
0.0